version: "3.8"

services:
  eureka-server:
    build: ./microservices/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  pedido-microservice:
    build: ./microservices/pedido-microservice
    container_name: pedido-microservice
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server

  producto-microservice:
    build: ./microservices/producto-microservice
    container_name: producto-microservice
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server

  pedidocomposition-microservice:
    build: ./microservices/pedidocomposition-microservice
    container_name: pedidocomposition-microservice
    ports:
      - "8083:8080"
    depends_on:
      - pedido-microservice
      - producto-microservice
      - eureka-server

  # Bases de datos
  pedido_db:
    image: postgres:15
    container_name: pedido_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pedido_user
      POSTGRES_PASSWORD: pedido_pass
      POSTGRES_DB: pedido_db

  producto_db:
    image: postgres:15
    container_name: producto_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: producto_user
      POSTGRES_PASSWORD: producto_pass
      POSTGRES_DB: producto_db

volumes:
  pedido_data:
  producto_data:
